package edu.tsystems.demail.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Author: Ivan Pastukh
 * Date: 18.06.13
 * Time: 19:47
 */
public class Test {
    private JPanel panel1;
    private JTree tree1;
    private JButton button1;
    private JList list1;

    public Test() {
        $$$setupUI$$$();
        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DefaultListModel listModel = new DefaultListModel();
                listModel.addElement("Jane Doe");
                list1.setModel(listModel);
//                int index = list.getSelectedIndex();
//                listModel.remove(index);
            }
        });
    }


    private void createUIComponents() {


    }

    public void start() {
        JFrame frame = new JFrame("Test");
        frame.setContentPane(new Test().panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("left:69dlu:noGrow,fill:p:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:noGrow,top:4dlu:noGrow,center:d:grow"));
        button1 = new JButton();
        button1.setText("Button");
        CellConstraints cc = new CellConstraints();
        panel1.add(button1, cc.xy(2, 1));
        list1 = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        defaultListModel1.addElement("1");
        defaultListModel1.addElement("2");
        defaultListModel1.addElement("3");
        defaultListModel1.addElement("4");
        defaultListModel1.addElement("5");
        list1.setModel(defaultListModel1);
        panel1.add(list1, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
