package edu.tsystems.demail.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import edu.tsystems.demail.Client;
import edu.tsystems.demail.DTO.*;
import edu.tsystems.demail.Validator;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.Arrays;

/**
 * Author: Ivan Pastukh
 * Date: 11.06.13
 * Time: 16:37
 */
public class RegistrationForm {
    private JButton submitButton;
    private JPanel panel1;
    private JTextField loginTextField;
    private JTextField firstNameTextField;
    private JTextField lastNameTextField;
    private JTextField phoneNumberTextField;
    private JPasswordField passwordPasswordField;
    private JPasswordField password2PasswordField;
    private JTextField mailBoxTextField;
    private JLabel mailBoxLabel;
    private JLabel loginLabel;
    private JLabel firstNameLabel;
    private JLabel lastNameLabel;
    private JLabel passwordLabel;
    private JLabel phoneNumberLabel;
    private static Validator validator = new Validator();
    private MailBoxDTO mailBoxDTO;

    public RegistrationForm() {
        $$$setupUI$$$();
        submitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    createNewUser();
                } catch (IOException e1) {
                    e1.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
                }
            }
        }
        );
        loginTextField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                super.keyReleased(e);
                mailBoxTextField.setText(loginTextField.getText() + "@demail.de");
            }
        });
    }

    private boolean validRegData() {
        boolean valid;
        valid = validator.checkUserName(loginTextField.getText());
        if (!valid) {
            JOptionPane.showMessageDialog(panel1, "Check login!");
            return false;
        }
        valid = validator.checkPassword(password2PasswordField.getPassword(), passwordPasswordField.getPassword());
        if (!valid) {
            JOptionPane.showMessageDialog(panel1, "Check password!");
            return false;
        }
        return true;
    }

    public void createNewUser() throws IOException {
        UserDTO userDTO = null;

        if (validRegData() && !findUser()) {
            //create new user
            RegDTO regDTO = new RegDTO(
                                        loginTextField.getText(),
                                        Arrays.toString(passwordPasswordField.getPassword()),
                                        firstNameTextField.getText(),
                                        lastNameTextField.getText(),
                                        phoneNumberTextField.getText()
                                       );
            Client.sendTask("REG", regDTO);
            userDTO = (UserDTO) Client.getAnswer();
            if (userDTO != null) {
                JOptionPane.showMessageDialog(panel1, "User " + userDTO.getLogin() + " is registered.");
            } else System.out.println("Error! User don't create!");

        }
    }

    public boolean findUser() throws IOException {
        LoginDTO loginDTO = new LoginDTO(
                                        loginTextField.getText(),
                                        Arrays.toString(passwordPasswordField.getPassword())
                                        );
        Client.sendTask("FIND_USER", loginDTO);
        loginDTO = (LoginDTO) Client.getAnswer();
        if (loginDTO == null) return false;
        JOptionPane.showMessageDialog(panel1, "User with login " + loginDTO.getLogin() + " exists!");
        return true;

    }


    public void createUI() {
        JFrame frame = new JFrame("RegistrationForm");
        frame.setContentPane(new RegistrationForm().panel1);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setLocation(285, 0);
        frame.setVisible(true);
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:216px:grow", "center:d:grow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow"));
        panel1.setName("panel1");
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-1)), null));
        submitButton = new JButton();
        submitButton.setText("Submit");
        submitButton.setMnemonic('S');
        submitButton.setDisplayedMnemonicIndex(0);
        CellConstraints cc = new CellConstraints();
        panel1.add(submitButton, cc.xy(1, 27));
        loginTextField = new JTextField();
        loginTextField.setText("user");
        panel1.add(loginTextField, cc.xy(1, 3));
        loginLabel = new JLabel();
        loginLabel.setText("Login");
        panel1.add(loginLabel, cc.xy(1, 1));
        firstNameLabel = new JLabel();
        firstNameLabel.setText("First name");
        panel1.add(firstNameLabel, cc.xy(1, 9));
        firstNameTextField = new JTextField();
        firstNameTextField.setText("myke");
        panel1.add(firstNameTextField, cc.xy(1, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        lastNameLabel = new JLabel();
        lastNameLabel.setText("Last Name");
        panel1.add(lastNameLabel, cc.xy(1, 13));
        lastNameTextField = new JTextField();
        lastNameTextField.setText("Djobs");
        panel1.add(lastNameTextField, cc.xy(1, 15, CellConstraints.FILL, CellConstraints.DEFAULT));
        passwordLabel = new JLabel();
        passwordLabel.setText("Password");
        panel1.add(passwordLabel, cc.xy(1, 17));
        phoneNumberLabel = new JLabel();
        phoneNumberLabel.setText("Phone number");
        panel1.add(phoneNumberLabel, cc.xy(1, 23));
        phoneNumberTextField = new JTextField();
        phoneNumberTextField.setText("32222");
        panel1.add(phoneNumberTextField, cc.xy(1, 25, CellConstraints.FILL, CellConstraints.DEFAULT));
        passwordPasswordField = new JPasswordField();
        passwordPasswordField.setText("123");
        panel1.add(passwordPasswordField, cc.xy(1, 19, CellConstraints.FILL, CellConstraints.DEFAULT));
        password2PasswordField = new JPasswordField();
        password2PasswordField.setText("123");
        panel1.add(password2PasswordField, cc.xy(1, 21, CellConstraints.FILL, CellConstraints.DEFAULT));
        mailBoxLabel = new JLabel();
        mailBoxLabel.setText("MailBox");
        panel1.add(mailBoxLabel, cc.xy(1, 5));
        mailBoxTextField = new JTextField();
        mailBoxTextField.setText("user@demail.de");
        panel1.add(mailBoxTextField, cc.xy(1, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        loginLabel.setLabelFor(loginTextField);
        firstNameLabel.setLabelFor(firstNameTextField);
        lastNameLabel.setLabelFor(lastNameTextField);
        passwordLabel.setLabelFor(passwordPasswordField);
        phoneNumberLabel.setLabelFor(phoneNumberTextField);
        mailBoxLabel.setLabelFor(mailBoxTextField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
