package edu.tsystems.demail.ui;

import edu.tsystems.demail.Client;
import edu.tsystems.demail.DTO.MailBoxDTO;
import edu.tsystems.demail.DTO.RegDTO;
import edu.tsystems.demail.DTO.UserDTO;
import edu.tsystems.demail.Validator;
//import edu.tsystems.demail.model.UserEntity;
//import edu.tsystems.demail.services.FolderService;
//import edu.tsystems.demail.services.MailBoxService;
//import edu.tsystems.demail.services.UserService;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.Arrays;

/**
 * Author: Ivan Pastukh
 * Date: 11.06.13
 * Time: 16:37
 */
public class RegistrationForm {
    private JButton submitButton;
    private JPanel panel1;
    private JTextField loginTextField;
    private JTextField firstNameTextField;
    private JTextField lastNameTextField;
    private JTextField phoneNumberTextField;
    private JPasswordField passwordPasswordField;
    private JPasswordField password2PasswordField;
    private JTextField mailBoxTextField;
//    private UserService userService = new UserService();
    private Validator validator = new Validator();
    private MailBoxDTO mailBoxDTO;

    public RegistrationForm() {
        submitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    createNewUser();
                } catch (IOException e1) {
                    e1.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
                }
            }
        }
        );
        loginTextField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                super.keyReleased(e);
                mailBoxTextField.setText(loginTextField.getText() + "@demail.de");
            }
        });
    }


    public void createNewUser() throws IOException {
        boolean valid = false;
//        UserService userService = new UserService();
//        validator;

        valid = validator.checkPassword(password2PasswordField.getPassword(), passwordPasswordField.getPassword());
        if (!valid) JOptionPane.showMessageDialog(panel1, "Check password!");
        if (valid) {
            //create new user
            RegDTO regDTO = new RegDTO(
                    loginTextField.getText(),
                    Arrays.toString(passwordPasswordField.getPassword()),
                    firstNameTextField.getText(),
                    lastNameTextField.getText(),
                    phoneNumberTextField.getText()
            );
            //create mail box for user
            Client.sendTask("REG", regDTO);
//            mailBoxDTO = (MailBoxDTO)Client.getAnswer();
//            createDefaultFolder();

        }

    }

//    private MailBoxDTO createMailBoxForUser(UserEntity userEntity) {
//        System.out.println("create mail box for user " + userEntity.getLogin());
//        UserDTO userDTO = new UserDTO();
//        userDTO.setId(userEntity.getId());
//        userDTO.setLogin(userEntity.getLogin());
//        MailBoxService mailBoxService = new MailBoxService();
//        mailBoxDTO = mailBoxService.createMailBox(userDTO);
//        return mailBoxDTO;
//
//    }

//    private void createDefaultFolder() {
//        System.out.println("create defaul folder for mail box " + mailBoxDTO.getMailbox());
//        FolderService folderService = new FolderService();
//        folderService.createDefaultFolderForMailBoxId(mailBoxDTO);
//    }

    public void createUI() {
        JFrame frame = new JFrame("RegistrationForm");
        frame.setContentPane(new RegistrationForm().panel1);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setLocation(285, 0);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(14, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setName("panel1");
        submitButton = new JButton();
        submitButton.setText("Submit");
        submitButton.setMnemonic('S');
        submitButton.setDisplayedMnemonicIndex(0);
        panel1.add(submitButton, new com.intellij.uiDesigner.core.GridConstraints(13, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(194, 26), null, 0, false));
        loginTextField = new JTextField();
        loginTextField.setText("user");
        panel1.add(loginTextField, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(194, 22), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Login");
        panel1.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(194, 14), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("First name");
        panel1.add(label2, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(194, 14), null, 0, false));
        firstNameTextField = new JTextField();
        firstNameTextField.setText("myke");
        panel1.add(firstNameTextField, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(194, 22), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Last Name");
        panel1.add(label3, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(194, 14), null, 0, false));
        lastNameTextField = new JTextField();
        lastNameTextField.setText("Djobs");
        panel1.add(lastNameTextField, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(194, 22), null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Password");
        panel1.add(label4, new com.intellij.uiDesigner.core.GridConstraints(8, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(194, 14), null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Phone number");
        panel1.add(label5, new com.intellij.uiDesigner.core.GridConstraints(11, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(194, 14), null, 0, false));
        phoneNumberTextField = new JTextField();
        phoneNumberTextField.setText("32222");
        panel1.add(phoneNumberTextField, new com.intellij.uiDesigner.core.GridConstraints(12, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(194, 22), null, 0, false));
        passwordPasswordField = new JPasswordField();
        passwordPasswordField.setText("123");
        panel1.add(passwordPasswordField, new com.intellij.uiDesigner.core.GridConstraints(9, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(194, 24), null, 0, false));
        password2PasswordField = new JPasswordField();
        password2PasswordField.setText("123");
        panel1.add(password2PasswordField, new com.intellij.uiDesigner.core.GridConstraints(10, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("MailBox");
        panel1.add(label6, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        mailBoxTextField = new JTextField();
        mailBoxTextField.setText("user@demail.de");
        panel1.add(mailBoxTextField, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        label1.setLabelFor(loginTextField);
        label2.setLabelFor(firstNameTextField);
        label3.setLabelFor(lastNameTextField);
        label4.setLabelFor(passwordPasswordField);
        label5.setLabelFor(phoneNumberTextField);
        label6.setLabelFor(mailBoxTextField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
